from rest_framework import serializers
from .models import Project

class ProjectSerializer(serializers.ModelSerializer):
    class Meta:
        model = Project
        fields = ('id', 'title', 'description', 'technology', 'created_at') # Fields we will be able to consult. Id is generated by deafault even if not specified.
        read_only_fields= ('created_at',) # Note the comma, if not placed it wouldn't be interpreted as a tuple but as a string